version: '3'

services:
  mongo: # Base de datos del core
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ./tmp/db:/data/db  

  core: # Core
    image: ghcr.io/democraciaenred/dialogo-legislativo-core:0.0.1
    env_file:
      - .env
    ports:
      - "4000:5000"
    depends_on:
      - mongo
    links:
      - mongo

  web: # App Web
    image: ghcr.io/democraciaenred/dialogo-legislativo-web:0.0.1
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - core
    links:
      - mongo

  notifier: # Notifier
    image: ghcr.io/democraciaenred/dialogo-legislativo-notifier:0.0.1
    env_file:
      - .env
    ports:
      - "5000:3000"
    depends_on:
      - core

  # postgres: # Base de datos de usuarios
  #   image: postgres:13.2
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - 5432:5432

  # auth: # Aplicación de autenticación
  #   image: ghcr.io/democraciaenred/auth_system:0.0.1
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres